<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>蓝莓AirPlay4K控制台</AssemblyName>
    <RootNamespace>BlueberryAirPlay4K</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\BlueberryAirPlay4K.ico</ApplicationIcon>
    <Version>3.1.1</Version>
    <FileVersion>3.1.1.0</FileVersion>
    <AssemblyVersion>3.1.1.0</AssemblyVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <PathMap>$(MSBuildProjectDirectory)=/_/src/BlueberryAirPlay4K</PathMap>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\BlueberryAirPlay4K.ico" />
  </ItemGroup>
</Project>
